spring.application.name=task3

spring.datasource.url=jdbc:postgresql://localhost:5432/students_database
spring.datasource.username=postgres
spring.datasource.password=password


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
